name:                conclave-hs
version:             0.1.0.0
github:              "lsocrate/conclave-hs"
license:             MIT
author:              "Luiz Socrate"
maintainer:          "luiz@socrate.com.br"

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.7 && < 5
- containers

default-extensions: DeriveAnyClass

library:
  source-dirs: src

executables:
  conclave-hs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - conclave-hs

tests:
  conclave-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - conclave-hs
